### ISSUE TITLE
Make command fails

### ISSUE THREAD

**Issue by whiletruelearn** [harkous/embeddingsviz#1]
Make command seems to be failing in Ubuntu 16.04

`make tests/test_blas
cc  tests/test_blas.cpp -o tests/test_blas  
/tmp/ccYHDv1a.o: In function `new_random_vec(int)':
test_blas.cpp:(.text+0x31): undefined reference to `operator new[](unsigned long)'
/tmp/ccYHDv1a.o: In function `main':
test_blas.cpp:(.text+0x106): undefined reference to `operator new[](unsigned long)'
test_blas.cpp:(.text+0x176): undefined reference to `sgemm_'
test_blas.cpp:(.text+0x2f0): undefined reference to `operator new[](unsigned long)'
test_blas.cpp:(.text+0x330): undefined reference to `sgeqrf_'
collect2: error: ld returned 1 exit status
Makefile:58: recipe for target 'tests/test_blas' failed
make: *** [tests/test_blas] Error 1
`

Any idea as to why ?

**Comment by harkous** [comment]
Hi,

Make sure you are following the instructions for Ubuntu 16 in the Faiss Makefile:
https://github.com/facebookresearch/faiss/blob/master/example_makefiles/makefile.inc.Linux#L65

The commands I provided are just to give an idea about how I installed Faiss under Ubuntu 14. Otherwise, the repository assumes you install Faiss already. If you didn't get it to work, you can open an issue at [Faiss](https://github.com/facebookresearch/faiss) repo.

Cheers!
